apiVersion: v1
kind: Service
metadata:
  name: demo-proxy
  labels:
    app: itsm-server
spec:
  selector:
    app: itsm-server
  ports:
    - name: https
      targetPort: 80
      port: 8083  
      protocol: TCP